<?php

global $alphabet;
$alphabet = array(
    'a' => 0,
    'b' => 1,
    'c' => 2,
    'd' => 3,
    'e' => 4,
    'f' => 5,
    'g' => 6,
    'h' => 7,
    'i' => 8,
    'j' => 9,
    'k' => 10,
    'l' => 11,
    'm' => 12,
    'n' => 13,
    'o' => 14,
    'p' => 15,
    'q' => 16,
    'r' => 17,
    's' => 18,
    't' => 19,
    'u' => 20,
    'v' => 21,
    'w' => 22,
    'x' => 23,
    'y' => 24,
    'z' => 25
);


function shift_cipher_menu(){
	$items = array();
    $items['shift_cipher'] = array(
        'title' => 'Shift Cipher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('shift_cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
     );
    $items['shift_cipher_success_page'] = array(
    'title' => 'Congrats!',
    'page callback' => 'shift_cipher_success',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
     );
   return $items;
}

function shift_cipher_form() {
    $form['shift_spaces'] = array(
      '#title' => 'Shift Spaces',
      '#type' => 'textfield',
      '#description' => t('Enter the number of spaces to shift.'),
      '#required' => TRUE,
      '#element_validate' => array('element_validate_integer', 'element_validate_number_range'),
    );
    return $form;
  }
